version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-preview2-sdk-alpine
    steps:
      - checkout
      - run: cd LipsCS/Source
      - run: dotnet restore Source.csproj
      - run: dotnet build
      - run: cd ../Test
      - run: dotnet test